version: "3.9"

services:
  sandbox:
    build:
      context: ./sandbox
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=2000
      - FLASK_APP=server.py

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5002
      - FLASK_APP=server.py
    volumes:
      - ./templates:/app/templates

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
