name: Full stack build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-compose:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🔧 Build and start containers
        run: docker compose --parallel up --build -d

      - name: 🧪 Wait for services to become healthy
        run: |
          echo "Waiting for sandbox and backend containers to be healthy..."
          timeout 60 bash -c '
          until [ "$(docker inspect -f "{{.State.Health.Status}}" $(docker compose ps -q sandbox))" = "healthy" ] && \
                [ "$(docker inspect -f "{{.State.Health.Status}}" $(docker compose ps -q backend))" = "healthy" ]; do
            echo "Still waiting..."
            sleep 2
          done
          '

      - name: 🧪 Run backend unit tests
        run: |
          docker compose exec backend \
            python -m unittest discover -s backend/tests -t . -p "test_*.py" -v

      - name: 🧪 Run sandbox unit tests
        run: |
          docker compose exec sandbox \
            python -m unittest discover -s sandbox/tests -t . -p "test_*.py" -v

      - name: 🌐 Check frontend availability
        run: |
          curl --fail http://localhost:8080 || (echo "Frontend not reachable" && exit 1)

      - name: 🧹 Tear down containers
        run: docker compose down
