name: Publish to PyPI on Release

on:
  release:
    types: [created]

permissions:
  contents: read  # needed for actions/checkout and uploading assets

jobs:
  build-and-publish:
    name: Build and Upload to PyPI
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🐍 Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: 📦 Install build backend
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: 🛠 Build sdist and wheel
      run: python -m build

    - name: 🚀 Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.11
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: 📎 Upload artifacts to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.whl
          dist/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
